### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by thom8047** [Eshop-project/CS-350#11]
There was a javascript written in to create a new shipping address object and the javascript worked on Vicente's computer but would throw a url POST error. The data wasn't being saved correctly. This contributed to the change in the guest user being the main focus of milestone 4.

**Comment by ramosv** [comment]
We talked on this issue for a little but it can be hard to pin point the exact issue while talking over the phone. This will definitely be something that we look at for the next time we meet.
