### ISSUE TITLE
Customer Issue #2

### ISSUE THREAD

**Issue by thom8047** [Eshop-project/CS-350#13]
The customer needed to be created along with a user. The user interface is built and only way to fix the first issue was to check if there was a customer object that had the same user as the authorized user. If not then create one for it. This fixed the first problem but leads us to here. The issue is if the user didn't make it to the store.html then the view wouldn't catch whether or not the user had a customer and make one if not. This slight problem will lead to issues down the road.

**Comment by ramosv** [comment]
We fix one issue and then another shows up. I agree with you that this is an issue that we can't forget about as it will probably lead to some more serious issues down the road. This shall be address at the next team meeting.
