### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by thom8047** [Eshop-project/CS-350#16]
There is not a lot of commented documentation. Even though we all work together, someone will usually say "I'll work on ..." and they do and it's usually a plug-in plug-out bit of code. We can use it or not and this works well in the group dynamic but is problematic because none of us really comment on our work to explain it.

**Comment by ramosv** [comment]
To fix issues like these we just got to look at all the files in our project and go line by line to find these comments because they really are all over the place. We are going to have to designate a chunk of time during this next milestone to do so.

**Comment by ramosv** [comment]
We have fixed this issues during our last team meeting
