### ISSUE TITLE
Issues With the cart

### ISSUE THREAD

**Issue by SProv7615** [Eshop-project/CS-350#26]
Hello. I did not make an account, but I did add items to the cart. There's two points I'd like to bring up: one is that it does not seem to display the size of the item that you've added to the cart, which seems a bit concerning. Secondly, if you add two of the same items to the cart, with different sizes,  they are added as the same item.

Those aside, very clean and professional looking.

**Comment by bryanaguilar22** [comment]
We will be working to be putting size on order.  Thank you for your feedback
