### ISSUE TITLE
Github issues

### ISSUE THREAD

**Issue by bryanaguilar22** [Eshop-project/CS-350#3]
We are having issues forking repos and keeping everything straight when we are all working on the same file.  It could be that we are not all added as contributors.  To avoid confusion I think it would be a good idea if we each had our own repository that starts from the base code we have so far.  Any thoughts?

**Comment by thom1664** [comment]
I agree, I think we can use the repo CS-350 as our main and contribute what we learn/code from our own repos while keeping documentation in one place.
