### ISSUE TITLE
Perhaps separate about and contact 

### ISSUE THREAD

**Issue by Adam1400** [Eshop-project/CS-350#30]
Over all good stuff! You guys have one of the best looking apps. Your use of bootstrap really makes the site pop! 
In terms of something to change... consider making different pages for "contact" and "about". Currently your contact and about sections both appear to go to the same place. 
Great site, nice work!

**Comment by thom1664** [comment]
Appreciate your kind feedback! We are taking your consideration into account and are making the changes currently.
